env_mattermost_token: "MATTERMOST_TOKEN"
mattermost_http:  "http://localhost:8065"
mattermost_websocket: "ws://localhost:8065"
team_name: "jira-mattermost"
messages_pattern: ".*jira!.*"
message_reply: "Make issue! Link: "