messenger: "rocketchat"
task_tracker: "yandex_tracker"
enable_msg_threating: true
storage_type: "postgres"
env_mattermost_token: "MATTERMOST_TOKEN"
mattermost_http:  "http://localhost:8065"
mattermost_websocket: "ws://localhost:8065"
mettermost_team_name: "jira-mattermost"
messages_pattern: ".*bug.*"
message_reply: "Make issue! Link: {{.Link}}"
task_name: "From {{.Messenger}}"
env_jira_bot_username: "JIRA_BOT_USERNAME"
env_jira_bot_password: "JIRA_BOT_PASSWORD"
jira_project: "TEST"
jira_issue_type: "Bug"
jira_base_url: "http://localhost:8080"
env_postgres_login: "DB_LOGIN"
env_postgres_password: "DB_PASSWORD"
postgres_host: "localhost"
postgres_port: "5432"
postgres_name: "db"
postgres_table_name: "messagestasks"
rocketchat_host: "localhost:3000"
rocketchat_http: "http://localhost:3000"
env_rocketchat_token: "ROCKETCHAT_TOKEN"
env_rocketchat_id: "ROCKETCHAT_USER_ID"
yandex_tracker_host: "http://api.tracker.yandex.net"
yandex_tracker_base_url: "https://tracker.yandex.ru"
env_yandex_tracker_id_organization: "YANDEX_TRACKER_ID_ORG"
yandex_tracker_type_organization: "X-Cloud-Org-ID"
yandex_tracker_token_type: "Bearer"
env_yandex_tracker_token: "YANDEX_TRACKER_TOKEN"
yandex_tracker_queue: "TESTY"
yandex_tracker_task_type: "bug"
