env_mattermost_token: "MATTERMOST_TOKEN"
mattermost_http:  "http://localhost:8065"
mattermost_websocket: "ws://localhost:8065"
team_name: "jira-mattermost"
messages_pattern: ".*jira!.*"
message_reply: "Make issue! Link: "
env_jira_bot_username: "JIRA_BOT_USERNAME"
env_jira_bot_password: "JIRA_BOT_PASSWORD"
jira_project: "TEST"
jira_issue_type: "Bug"
jira_url: "http://localhost:8080"